xx_pointage_encaissement:
    path: /pointage_encaissement/liste/{type}/{mode}/{date}
    methods: [GET, POST]
    defaults:
        _controller: 'PrestaShop\Module\PointageEncaissementBoutique\Controller\Admin\ListOrderController::indexAction'

xx_acceuil_pointage_encaissement:
    path: /pointage_encaissement/acceuil
    methods: [GET, POST]
    defaults:
        _controller: 'PrestaShop\Module\PointageEncaissementBoutique\Controller\Admin\ListOrderController::indexActionAccueil'