xx_pointage_encaissement:
    path: /pointage_encaissement/{type}/{mode}/{date}
    methods: [GET, POST]
    defaults:
        _controller: 'PrestaShop\Module\PointageEncaissementBoutique\Controller\Admin\ListOrderController::indexAction'