xx_pointage_encaissement:
    path: /pointage_encaissement/pointage
    methods: [GET]
    defaults:
        _controller: 'PrestaShop\Module\PointageEncaissementBoutique\Controller\Admin\TaskController::createForm_PointageEncaissementBoutique_Pointage_Afficher'

xx_acceuil_pointage_encaissement:
    path: /pointage_encaissement/acceuil
    methods: [GET]
    defaults:
        _controller: 'PrestaShop\Module\PointageEncaissementBoutique\Controller\Admin\TaskController::createForm_PointageEncaissementBoutique_Accueil_Afficher'